version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cms-challenge-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: challenge_admin
      POSTGRES_PASSWORD: Sup3rSecret2024
      POSTGRES_DB: challenge_qa
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
